### ISSUE TITLE
Specify username as commandline argument

### ISSUE THREAD

**Issue by erikwt** [grahamc/ish#3]
A handy feature would be to allow the username to be specified as an argument, rather than having to create a config file for each host. Is that something you would consider working on?

**Comment by grahamc** [comment]
Hi there,

I'm sorry I didn't get back to you sooner -- this slipped off my radar.

How many servers do you have with different usernames? Can you tell me anything else about your situation?

I'm trying to come up with a decision on this now.

Graham

**Comment by grahamc** [comment]
I'm going to go ahead and close this for now. Let me know if you have renewed interest.
